### ISSUE TITLE
sort-lines package not intalling

### ISSUE THREAD

**Issue by jeymz27** [atom/sort-lines#106]
### Description

sort-lines version 0.19.0 package is not getting installed due to certificate issue

### Steps to Reproduce

1. Try to install the package from the CLI / or from the atom UI(clicking install button)
2. package wont install

**Expected behavior:** Package should install successfully

**Actual behavior:** System generates the following error : 

npm ERR! code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
npm ERR! request to https://registry.npmjs.org/javascript-natural-sort failed, reason: unable to get local issuer certificate

Logged in log
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/jraopot/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/jraopot/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/sort-lines/versions/0.19.0/tarball',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session 7fe0234099de4ef6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://www.atom.io/api/packages/sort-lines/versions/0.19.0/tarball 1465ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/sort-lines/versions/0.19.0/tarball fetched in 1479ms
9 timing stage:loadCurrentTree Completed in 1629ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule sort-lines@0.19.0 checking installable status
17 silly fetchPackageMetaData error for javascript-natural-sort@^0.7.1 request to https://registry.npmjs.org/javascript-natural-sort failed, reason: unable to get local issuer certificate
18 silly fetchPackageMetaData error for array-shuffle@^1.0.1 request to https://registry.npmjs.org/array-shuffle failed, reason: unable to get local issuer certificate
19 timing stage:rollbackFailedOptional Completed in 0ms
20 timing stage:runTopLevelLifecycles Completed in 2033ms
21 silly saveTree apm-install-dir-12076-62632-1tecdmg.gh0sg
21 silly saveTree └── sort-lines@0.19.0
22 verbose type system
23 verbose stack FetchError: request to https://registry.npmjs.org/javascript-natural-sort failed, reason: unable to get local issuer certificate
23 verbose stack     at ClientRequest.req.on.err (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
23 verbose stack     at ClientRequest.emit (events.js:182:13)
23 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:382:9)
23 verbose stack     at TLSSocket.emit (events.js:182:13)
23 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
23 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
23 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
24 verbose cwd /private/var/folders/d6/19vy0mbj5_9c3b8hbq8k2c2xmr57gr/T/apm-install-dir-12076-62632-1tecdmg.gh0sg
25 verbose Darwin 19.2.0
26 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/jraopot/.atom/.apm/.apmrc" "--userconfig" "/Users/jraopot/.atom/.apmrc" "install" "https://www.atom.io/api/packages/sort-lines/versions/0.19.0/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
27 verbose node v10.2.1
28 verbose npm  v6.2.0
29 error code UNABLE_TO_GET_ISSUER_CERT_LOCALLY
30 error errno UNABLE_TO_GET_ISSUER_CERT_LOCALLY
31 error request to https://registry.npmjs.org/javascript-natural-sort failed, reason: unable to get local issuer certificate
32 verbose exit [ 1, true ]

**Reproduces how often:** Everytime

### Versions
Atom --version
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.16
git 2.24.3

OS : MAC OS - Catalina

**Comment by sadick254** [comment]
Thanks for opening the issue!
Am unable to reproduce the bug.
```
Atom    : 1.50.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.16
git 2.24.3

 OS: macOS Catalina 10.15.6 19G73 x86_64
```

Can you confirm that you are still unable to install `sort-lines`

**Comment by ladar** [comment]
I'm also getting an install erorr, but it appears to be a different issue:

```
curl https://www.atom.io/api/packages/sort-lines/versions/0.19.0/tarball
{"message":"Application error"}
```

I tried from different systems, on different networks, and both got the same result.
