### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of undefined

### ISSUE THREAD

**Issue by justCxx** [atom/sort-lines#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [sort-lines](https://github.com/atom/sort-lines) package, v0.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of undefined

```
At /home/justcxx/.atom/packages/sort-lines/lib/range-finder.coffee:23

TypeError: Cannot read property 'getSelectedBufferRanges' of undefined
  at RangeFinder.module.exports.RangeFinder.selectionRanges (/home/justcxx/.atom/packages/sort-lines/lib/range-finder.coffee:23:12)
  at RangeFinder.module.exports.RangeFinder.ranges (/home/justcxx/.atom/packages/sort-lines/lib/range-finder.coffee:14:24)
  at Function.module.exports.RangeFinder.rangesFor (/home/justcxx/.atom/packages/sort-lines/lib/range-finder.coffee:7:29)
  at sortTextLines (/home/justcxx/.atom/packages/sort-lines/lib/sort-lines.coffee:20:32)
  at sortLines (/home/justcxx/.atom/packages/sort-lines/lib/sort-lines.coffee:27:4)
  at atom-text-editor.atom.commands.add.sort-lines:sort (/home/justcxx/.atom/packages/sort-lines/lib/sort-lines.coffee:8:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:241:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -3:39.4.0 grammar-selector:show (atom-text-editor.editor)
     -1:37.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:21.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:19.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:19.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:14.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:13.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:12.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:09.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -1:09.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -1:06.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:56.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -0:56 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:50.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -0:50.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 sort-lines:sort (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-python-pep8",
      "linter-python-pep8",
      "linter-jscs",
      "linter",
      "atom-language-xquery",
      "atom-language-xquery",
      "autocomplete-plus-python-jedi",
      "linter-ansible-lint",
      "linter-ansible-lint",
      "linter-ansible-lint",
      "linter-ansible-lint",
      "linter-ansible-lint"
    ],
    "ignoredNames": [
      ".pyc"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.8
atom-python-debugger, v0.3.4
atom-xsltransform, v0.2.0
autocomplete-python, v0.5.1
file-icons, v1.5.8
jsformat, v0.9.0
language-ansible, v0.1.3
linter-cpplint, v0.1.4
linter-jshint, v0.1.7
linter-pep257, v0.2.1
linter-pep8, v0.2.0
linter-xmllint, v0.0.7
minimap, v4.10.1
pretty-json, v0.4.1
python-isort, v0.0.7
python-yapf, v0.7.0
sort-lines, v0.11.0
svg-preview, v0.6.0
svn, v0.0.6
tag, v0.3.0
terminal-status, v1.6.8
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by Tyriar** [comment]
This is caused by triggering sort on a mini text editor.
